#ifndef OIR_CLI_PASS_H
#define OIR_CLI_PASS_H

#include <stdio.h>

typedef enum {
  PASS_ANALYZE_LIVENESS,
  PASS_ANALYZE_REACHING_DEFINITION,
  PASS_ANALYZE_AVAILABLE_EXPRESSION,
  PASS_OPTIMIZE_DEAD_CODE_ELIMINATION,
  PASS_OPTIMIZE_PROPAGATION,
  PASS_OPTIMIZE_COMMOM_SUBEXPRESSION_ELIMINATION,
} Pass;

void print_Pass(FILE*, Pass);
Pass parse_Pass(const char*);

#endif
