on: push

name: latest

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debug: [1, 0]
        sanitizer: [1, 0]
        compiler: [gcc, clang]
        exclude:
          - debug: 0
            sanitizer: 1
    steps:
    - uses: actions/checkout@master
    - run: make test.docker
      env:
        DEBUG: ${{ matrix.debug }}
        SANITIZER: ${{ matrix.sanitizer }}
        CC: ${{ matrix.compiler }}
        # TODO: remove memory leaks
        ASAN_OPTIONS: detect_leaks=0
  check_style:
    name: check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: make style.docker
    - run: git diff --exit-code
