on: push

name: latest

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debug: [1, 0]
        sanitizer: [1, 0]
        compiler: [gcc, clang]
        exclude:
          - debug: 0
            sanitizer: 1
    steps:
    - uses: actions/checkout@master
    - run: make test.image
      env:
        DEBUG: ${{ matrix.debug }}
        SANITIZER: ${{ matrix.sanitizer }}
        CC: ${{ matrix.compiler }}
  check_style:
    name: code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Prepare run-clang-format
      run: |
        wget https://github.com/Sarcasm/run-clang-format/blob/master/run-clang-format.py
        chmod +x run-clang-format.py
    - run: ./run-clang-format.py -r src
